# Prometheus server config file for the IPFS indexing infrastructure.
global:
  scrape_interval:     15s # Default is every 1 minute.
  #evaluation_interval: 20s # The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # Metrics provided by kubo itself.
  # These are exposed at <API address>/debug/metrics/prometheus
  - job_name: 'kubo'
    metrics_path: '/debug/metrics/prometheus'
    static_configs:
      - targets: ['daemon01:5001', 'daemon02:5001']

  # Metrics about the host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # The CID worker.
  - job_name: 'cid-worker'
    static_configs:
      - targets: ['cid_worker:8088']

  # The block workers.
  - job_name: 'block-worker'
    static_configs:
      - targets: ['block_worker_daemon01:8088','block_worker_daemon02:8088']

  # The file workers.
  - job_name: 'file-worker'
    static_configs:
      - targets: ['file_worker_daemon01:8088','file_worker_daemon02:8088']

  # The directory workers
  - job_name: 'directory-worker'
    static_configs:
      - targets: ['directory_worker_daemon01:8088','directory_worker_daemon02:8088']

  # The HAMTShard workers
  - job_name: 'hamtshard-worker'
    static_configs:
      - targets: ['hamtshard_worker_daemon01:8088','hamtshard_worker_daemon02:8088']

#  # RabbitMQ, aggregated metrics
#  - job_name: 'rabbitmq'
#    static_configs:
#      - targets: ['rmq:15692']

  # RabbitMQ, per-object metrics
  - job_name: 'rabbitmq-per-object'
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ['rmq:15692']